### ISSUE TITLE
Infinite job loop

### ISSUE THREAD

**Issue by MarcoMartins86** [rheirman/GiddyUpRideAndRoll#8] opened 2018-12-08 17:51 UTC
Hi, I have noticed an issue with this mod which makes paws on an infinite loop trying to do a job until they break down. Until now it only happened to me when trying to refuel things with wood but I suspect that it is more connected to a weight problem.

Infinite job loop pawn behavior:
1. Riding to the job: "Refueling something with wood"
2. When he reaches the wood, he doesn't pick it up and changes the job to "Hauling something" while adding to queue the "Refueling something with wood" job
3. Do the hauling job correctly, starting the queued job "Refueling something with wood"
4. Last steps repeat forever

Ride: 
- Husky

Pawn Inventory:
- Charge Lance
- Plasteel advance helmet
- Heavy fur tribalwear
- Marine armor
- Medical bag (Field Medic mod https://github.com/flyfire2002/RimworldFieldMedic)

**Comment by rheirman** [comment] 2019-05-13 08:27
I can't reproduce this. Maybe it was an issue with an older version?

**Comment by jinlan** [comment] 2019-05-13 10:14
Are you using LWM's Deep Storage?
That mod can cause infinite loop.
The author has just updated his mod.

**Comment by rheirman** [comment] 2019-05-15 13:34
I'm closing this issue as I can't reproduce it. Let me know if it's still a thing with the latest build, then I'll reopen it.

**Closed as completed** 2019-05-15 13:35 UTC

**Comment by MarcoMartins86** [comment] 2019-05-15 19:15
In my last plays (about a month ago) I didn't remember this happening, maybe I was using the mentioned mod at the time. So yeah for me this is closed. Although, I remember happening more than once, that pawns rarely would just freeze forever while doing automated tasks while mounting. I had to draft and un-draft pawn for him to stop being frozen. Nevertheless, I will open another issue if it is still happening next time I play.

Thank you.
